name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:       # 👈 esto va dentro del job, al mismo nivel que runs-on
      contents: write 

    strategy:
      matrix:
        node-version: [18.x]   # solo una versión basta para deploy

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./react-app/package-lock.json

      - name: Install dependencies
        working-directory: ./react-app
        run: npm install

      - name: Build project
        working-directory: ./react-app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./react-app/build
